delete from public."Haulage_Driver_Vehicle";
delete from public."Driver_Notification";
delete from public."Haulage";
delete from public."Cargo";
delete from public."Route";
delete from public."User";
delete from public."Driver_Vehicle";
delete from public."Driver";
delete from public."Vehicle";